<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    // Default status 'confirmed' matches Flutter OrdersController.addFromCheckout()
    // order_number generated by OrderService with DB lock — replaces Flutter timestamp-modulo
    // user_id nullable — prepared for future guest checkout
    public function up(): void
    {
        Schema::create('orders', function (Blueprint $table) {
            $table->id();
            $table->string('order_number', 20)->unique();

            $table->foreignId('user_id')
                  ->nullable()
                  ->constrained('users')
                  ->nullOnDelete();

            // Customer data snapshotted at order time — never joined to users
            $table->string('customer_name', 255);
            $table->string('customer_phone', 30);
            $table->string('customer_city', 255);
            $table->text('customer_address');
            $table->text('customer_notes')->nullable();

            $table->string('payment_method', 50)->default('cod');

            $table->enum('status', [
                'pending', 'confirmed', 'preparing',
                'shipping', 'delivered', 'cancelled',
            ])->default('confirmed');

            $table->decimal('shipping_cost', 10, 2)->default(2.00);
            $table->decimal('total_amount', 10, 2);
            $table->timestamps();
            $table->softDeletes();

            $table->index('user_id');
            $table->index('status');
            $table->index('payment_method');
            $table->index('deleted_at');
            $table->index(['user_id', 'created_at'], 'idx_orders_user_date');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('orders');
    }
};
